name: Release

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Build manifests
        run: make release-manifests
      - name: Release manifests
        uses: softprops/action-gh-release@26994186c0ac3ef5cae75ac16aa32e8153525f77 # v1
        with:
          files: |
            _output/components.yaml
            _output/high-availability.yaml
            _output/high-availability-1.21+.yaml
      - name: Build binaries
        run: make build-all
      - name: Release binaries
        uses: softprops/action-gh-release@26994186c0ac3ef5cae75ac16aa32e8153525f77 # v1
        with:
          files: |
            _output/metrics-server-*
